name: GitHub CD

on:
  push:
    tags:
      - trellis-extensions-[0-9]+.[0-9]+.[0-9]+

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1

  build:
    runs-on: ubuntu-latest
    needs: [validation]
    strategy:
      matrix:
        java: [11]

    name: Java ${{ matrix.java }} environment

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}

    - name: Build with Gradle
      run: ./gradlew check assemble javadoc -x pmdMain

  docker:
    needs: [build]
    runs-on: ubuntu-latest

    name: Deploy docker container
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 11

    - name: Publish Docker Container
      run: |
        docker login docker.pkg.github.com -u $GITHUB_ACTOR -p "${{ secrets.GITHUB_TOKEN }}"
        ./buildtools/src/main/resources/docker/publishToGitHub.sh

